sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: dFOMObExXFdqSbM6Y/PAuWDixgosCFrqqCsy2dLGbssfLWdqn6yFpibYi4cwfrqCrz6/J1V14EjMXdIXCN6wZW0iEOnT8NrbcLOKuVaLV+tyYsSVeVcxbssTJGdh3o0ePNUtQr8g0qikTP9vQWeUJNDeTqgq5THqewf7AWNA/iifBk0qnBxgy4gq3vpbAEolQR+KWcH7NATiTED0a2kwvas8v7QS22nFLI4VIOCB96H93Y+R4F6jLo0qD4z2H3c5mEp8f2oavWOsxXRIaYiK5JH1zvDAClvY04cLEUTaLmlC2DA3mHSdFKPudL6W1tYC1KZQYYur7FAqMwKKR1cq/K6CNU95W/0WqGVSn7sVabAsHm8hJoc9ovKakjGXE/lt6R9tf+lJieAWUxvI90en/S0tEsjPm+bkWirsCGo+HOpH+/YZZc6HAS0GbK7daQsFQ5p9gGs1u0M2nuPHPhNpXiLIIXig0AS2LYep82ch9nYER2Lmhv+EDXxBOHE4z7wZ0MWC0VTPXLQXnH52MxUe1P/vu5yr1vekFju5HjT9UsA9VPMh+3NJ9vdPZzrVSoaYi1fofm9ery2p5Bz0NpKGAgOTkBfds9T7SZr9BG9Pxp4hHHdKWyRU4hcXr+9MbmfaRyQqnT7QiynMClMu26hKQVfSiIVI+1Qh7nFNWwjcB/0=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Memoirs-of-Napoleon-Bonaparte---Complete_3567
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy